name: Publish pypirccua to PyPI

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # setup Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      # build the package
      - name: Build the package
        run: python -m build

      # publish to PyPI
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}  # Use the PyPI username from secrets
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}  # Use the PyPI password/token from secrets
        run: |
          python -m twine upload dist/*

      # post-publish cleanup
      - name: Cleanup build artifacts
        run: rm -rf dist build *.egg-info
